version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run: node --version
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install libudev-dev libusb-1.0-0-dev
      - run: yarn install
      - run: yarn eslint
      - run: yarn build-js
      - run: yarn test-unit
      - run: yarn build
      - run: yarn test-bin
      - run: yarn audit
workflows:
  node-tests:
    jobs:
      - build